# Generated by Django 3.2.4 on 2021-06-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plants',
            name='climet',
            field=models.CharField(blank=True, default=' ', max_length=500),
        ),
        migrations.AddField(
            model_name='plants',
            name='dead_recycle',
            field=models.CharField(blank=True, default=' ', max_length=500),
        ),
        migrations.AddField(
            model_name='plants',
            name='flower_details',
            field=models.CharField(blank=True, default=' ', max_length=500),
        ),
        migrations.AddField(
            model_name='plants',
            name='flower_feature',
            field=models.CharField(blank=True, default=' ', max_length=500),
        ),
        migrations.AddField(
            model_name='plants',
            name='how_to_care',
            field=models.CharField(blank=True, default=' ', max_length=500),
        ),
        migrations.AddField(
            model_name='plants',
            name='how_to_glow',
            field=models.CharField(blank=True, default=' ', max_length=500),
        ),
        migrations.AddField(
            model_name='plants',
            name='how_to_plant',
            field=models.CharField(blank=True, default=' ', max_length=500),
        ),
        migrations.AddField(
            model_name='plants',
            name='life_cycle',
            field=models.CharField(blank=True, default=' ', max_length=500),
        ),
        migrations.AddField(
            model_name='plants',
            name='medi_detail',
            field=models.CharField(blank=True, default=' ', max_length=500),
        ),
        migrations.AddField(
            model_name='plants',
            name='no_of_species',
            field=models.CharField(blank=True, default=' ', max_length=500),
        ),
        migrations.AddField(
            model_name='plants',
            name='organic_manure',
            field=models.CharField(blank=True, default=' ', max_length=500),
        ),
        migrations.AddField(
            model_name='plants',
            name='smell',
            field=models.CharField(blank=True, default=' ', max_length=500),
        ),
        migrations.AddField(
            model_name='plants',
            name='soil',
            field=models.CharField(blank=True, default=' ', max_length=500),
        ),
        migrations.AddField(
            model_name='plants',
            name='water',
            field=models.CharField(blank=True, default=' ', max_length=500),
        ),
        migrations.AddField(
            model_name='plants',
            name='year_scient_name',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='plants',
            name='family_name',
            field=models.CharField(blank=True, default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='plants',
            name='origin',
            field=models.CharField(blank=True, default=' ', max_length=500),
        ),
        migrations.AlterField(
            model_name='plants',
            name='pic1',
            field=models.FileField(default=' ', upload_to='plant_gallery/'),
        ),
        migrations.AlterField(
            model_name='plants',
            name='pic2',
            field=models.FileField(default=' ', upload_to='plant_gallery/'),
        ),
        migrations.AlterField(
            model_name='plants',
            name='pic3',
            field=models.FileField(default=' ', upload_to='plant_gallery/'),
        ),
        migrations.AlterField(
            model_name='plants',
            name='pic4',
            field=models.FileField(default=' ', upload_to='plant_gallery/'),
        ),
        migrations.AlterField(
            model_name='plants',
            name='reg_sif_name',
            field=models.CharField(blank=True, default=' ', max_length=500),
        ),
        migrations.AlterField(
            model_name='plants',
            name='sif_name',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='plants',
            name='simple_name',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
