# Generated by Django 3.2.4 on 2021-06-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210619_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plants',
            name='dead_recycle',
        ),
        migrations.RemoveField(
            model_name='plants',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='plants',
            name='reg_sif_name',
        ),
        migrations.RemoveField(
            model_name='plants',
            name='soil',
        ),
        migrations.RemoveField(
            model_name='plants',
            name='water',
        ),
        migrations.RemoveField(
            model_name='plants',
            name='year_scient_name',
        ),
        migrations.AddField(
            model_name='plants',
            name='category',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
