# Generated by Django 3.2.4 on 2021-06-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210619_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='sering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.FileField(default=' ', upload_to='search/')),
            ],
        ),
    ]
