# Generated by Django 3.2.4 on 2021-06-20 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_sering'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sering',
        ),
    ]
